# Generated by Django 3.1 on 2020-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('Fever', models.CharField(max_length=20)),
                ('Bodypain', models.CharField(max_length=20)),
                ('runnyNose', models.CharField(max_length=20)),
                ('BreathDiffl', models.CharField(max_length=20)),
            ],
        ),
    ]
